# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2020-02-25 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('label', models.TextField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.ChatRoom'),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
