# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2020-02-25 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200225_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
