# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2020-02-25 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20200225_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='handle',
            field=models.EmailField(max_length=254),
        ),
    ]
